parameters:
    ezobject_wrapper.repository.abstract.class: Kaliop\eZObjectWrapperBundle\Core\Repository

services:

    Kaliop\eZObjectWrapperBundle\Core\EntityManager:
        public: true
        arguments:
          - '@ezpublish.api.repository'
          # map of fieldtypes => classes implementing RepositoryInterface. The repos will be created on the fly by the EM.
          # Using this type of declaration makes it easy to add repos without having to declare services.
          - []

    # base service for all Repository services, allows to inject the logger
    ezobject_wrapper.repository.abstract:
        class: '%ezobject_wrapper.repository.abstract.class%'
        calls:
            - [ setLogger, [ '@?logger' ] ]
        abstract: true

    twig.extension.ezobject_wrapper:
        class: Kaliop\eZObjectWrapperBundle\Twig\eZObjectWrapperExtension
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.view_manager'
        tags:
            - { name: twig.extension }
